import React from 'react';
import Head from "next/head";
import dynamic from "next/dynamic";

const ComponentWithNoSSR = dynamic(
	() => import('../../components/Anime'),
	{ ssr: false }
)


const Home = () => {

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app"/>
				<link rel="icon" href="/favicon.ico"/>
			</Head>

			<main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
				<ComponentWithNoSSR />
			</main>
		</>
	)
}

export default Home;